[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m venv .venv",
  ".venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = ".venv/bin/python -m uvicorn api:app --host 0.0.0.0 --port $PORT"
